version: "3"         
services:            
    server:          
      image: wishlist
      container_name: wishlist
      ports:                                                                                        
        - "5000:5000"
      depends_on:
        - db 
      environment:                                                                                  
        - APP_HOST=hramovdev.ru                                                                     
        - APP_PORT=5000                                                                             
        - DB_HOST=db 
        - DB_PORT=5432
        - DB_USER=postgres                                                                     
        - DB_PASSWORD=grafserega1997                                                         
        - DB_NAME=wishlist                                        
        - TOKEN=2057752320:AAFdlHgxrXt5LndoaPHZ9iq4cTXGqNJ4YEk
      networks:
        - postgres
    
    db:
      image: postgres
      container_name: wl_db
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=grafserega1997 
        - POSTGRES_DB=wishlist
        - PG_DATA=/data/postgres
      volumes:
        - postgres:/data/postgres
        - ./static/sql:/docker-entrypoint-initdb.d/
      networks:
        - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
